reliability_margin_factor: 0.0
min_ram: 0.0

cne_setting: all
line_usage_threshold: 0.2
cne_list: null
cne_reference_case_flows: NODAL_OPTIMUM
security_constraint_bodf_size_threshold: 0.2
security_constraint_bodf_columnwise_matrix_size_limit: 5000000

gsk_strategy: CURRENT_GENERATION
gsk_kwargs:
  ADJUSTABLE_CAP:
    adjustable_carriers: [CCGT, coal, lignite, OCGT, oil]
  ITERATIVE_UNCERTAINTY:
    uncertain_carriers: [offshore-wind, onshore-wind]
    num_scenarios: 100
    gen_variation_std_dev: 0.5
    load_variation_std_dev: 0.5
  ITERATIVE_FBMC:
    uncertain_carriers: [offshore-wind, onshore-wind]
    num_scenarios: 100
    max_gsk_iterations: 5
    initial_gsk_strategy: BUS_P
    gen_variation_std_dev: 0.5
    load_variation_std_dev: 0.5
  MERIT_ORDER:
    standard_deviation: 5
  BUS_P: {}

base_case_strategy: ZERO_FLOWS
marginal_cost_load_shedding: 100_000.0 # EUR/MWh

add_security_constraints: false
advanced_hybrid_coupling_flag: false

fbmc_solver_kwargs:
  solver_name: gurobi

run_redispatch: true
security_constrained_redispatch: false
deviation_factor_redispatch: 0.9

rd_solver_kwargs:
  solver_name: gurobi


